# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # Updated to the latest version

    - name: Setup Node.js
      uses: actions/setup-node@v3 # Ensure Node.js version is specified
      with:
        node-version: '18' # Or specify the Node.js version you need
        cache: 'npm'       # Enable npm caching

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
          ~/.cache/Cypress
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install modules
      run: npm install
    - name: Verify Cypress installation (if binary missing)
      run: npx cypress install # Install Cypress binary if missing
    - name: Run Cypress tests
      run: npm run ci:e2e
